import dotenv from 'dotenv';
import 'reflect-metadata'; // Usa por causa dos decorators
import express,{Request, Response, NextFunction} from 'express';
import 'express-async-errors';
import routes from './routes';
import './database';
import AppError from './errors/AppError';

dotenv.config();

const app = express();

app.use(express.json());

app.use(routes);

app.use((erro: AppError, request : Request,  response : Response, next : NextFunction) => {
    // Quer dizer que o erro foi originado pelo AppError, entÃ£o Ã© um erro que jÃ¡ conhecemos
    if(erro instanceof AppError){
        return response.status(erro.statusCode).json({
            status: 'Erro',
            message: erro.mensagem,
        });
    }
    
    // A partir daqui Ã© um erro desconhecido, que serÃ¡ necessÃ¡rio o uso do console para poder identificar
    console.error(erro);
    
    return response.status(500).json({
        status : 'Erro',
        message: 'Erro interno no serviror',
    })
});

app.listen(3333, () => {
    console.log(' ');
    console.log('Servidor rodando... ðŸš€');
    console.log('http://localhost:3333/');
    console.log(' ');
});